version: '3.9'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mongoDB

  mongoDB:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
