version: '3.9'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - MONGO_DB_URL=mongodb://host.docker.internal:27017
    ports:
      - "5000:5000"
    depends_on:
      - mongoDB

  mongoDB:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
